# Generated by Django 4.0.4 on 2022-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('blog_title', models.CharField(max_length=200)),
                ('content_blog', models.CharField(max_length=2000)),
                ('blog_photo', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
