# Generated by Django 4.0.4 on 2022-05-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='blog_photo',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
